# 1. Chargement des librairies

In [2]:
# Load libraries
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

C:\ProgramData\Anaconda3\envs\ia\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

# 2. Importer les données

In [3]:
cancer = pd.read_csv("cancer.csv")

# 3. Visualiser les premières lignes du jeu de données

In [4]:
cancer.head(5)

,"diagnosis(1=m, 0=b)",radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# 4. Visualiser les caractéristiques du jeu de données (nombre de lignes et de colonnes)

In [5]:
cancer.shape

(569, 31)

# 5. Vérifier les noms des colonnes

In [6]:
cancer.columns

Index(['diagnosis(1=m, 0=b)', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

# 6. Vérifier les types de données

In [7]:
cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   diagnosis(1=m, 0=b)      569 non-null    int64
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), int64(1)
memory usage: 137.9 KB

In [8]:
len(cancer.select_dtypes(include="int64").columns)

1

In [9]:
len(cancer.select_dtypes(include="float64").columns)

30

# 7. Vérifier la présence de doublons dans le jeu de données

In [10]:
len(cancer[cancer.duplicated()])

0

# 8. Analyse descriptive du jeu de données

In [19]:
cancer.describe().T

,count,mean,std,min,25%,50%,75%,max
diagnosis,569.0,0.372583,0.483918,0.000000,0.000000,0.000000,1.000000,1.00000
radius_mean,569.0,14.127292,3.524049,6.981000,11.700000,13.370000,15.780000,28.11000
texture_mean,569.0,19.289649,4.301036,9.710000,16.170000,18.840000,21.800000,39.28000
perimeter_mean,569.0,91.969033,24.298981,43.790000,75.170000,86.240000,104.100000,188.50000
area_mean,569.0,654.889104,351.914129,143.500000,420.300000,551.100000,782.700000,2501.00000
smoothness_mean,569.0,0.096360,0.014064,0.052630,0.086370,0.095870,0.105300,0.16340
compactness_mean,569.0,0.104341,0.052813,0.019380,0.064920,0.092630,0.130400,0.34540
concavity_mean,569.0,0.088799,0.079720,0.000000,0.029560,0.061540,0.130700,0.42680
concave points_mean,569.0,0.048919,0.038803,0.000000,0.020310,0.033500,0.074000,0.20120
symmetry_mean,569.0,0.181162,0.027414,0.106000,0.161900,0.179200,0.195700,0.30400
fractal_dimension_mean,569.0,0.062798,0.007060,0.049960,0.057700,0.061540,0.066120,0.09744
radius_se,569.0,0.405172,0.277313,0.111500,0.232400,0.324200,0.478900,2.87300
texture_se,569.0,1.216853,0.551648,0.360200,0.833900,1.108000,1.474000,4.88500
perimeter_se,569.0,2.866059,2.021855,0.757000,1.606000,2.287000,3.357000,21.98000
area_se,569.0,40.337079,45.491006,6.802000,17.850000,24.530000,45.190000,542.20000
smoothness_se,569.0,0.007041,0.003003,0.001713,0.005169,0.006380,0.008146,0.03113
compactness_se,569.0,0.025478,0.017908,0.002252,0.013080,0.020450,0.032450,0.13540
concavity_se,569.0,0.031894,0.030186,0.000000,0.015090,0.025890,0.042050,0.39600
concave points_se,569.0,0.011796,0.006170,0.000000,0.007638,0.010930,0.014710,0.05279
symmetry_se,569.0,0.020542,0.008266,0.007882,0.015160,0.018730,0.023480,0.07895
fractal_dimension_se,569.0,0.003795,0.002646,0.000895,0.002248,0.003187,0.004558,0.02984
radius_worst,569.0,16.269190,4.833242,7.930000,13.010000,14.970000,18.790000,36.04000
texture_worst,569.0,25.677223,6.146258,12.020000,21.080000,25.410000,29.720000,49.54000
perimeter_worst,569.0,107.261213,33.602542,50.410000,84.110000,97.660000,125.400000,251.20000
area_worst,569.0,880.583128,569.356993,185.200000,515.300000,686.500000,1084.000000,4254.00000
smoothness_worst,569.0,0.132369,0.022832,0.071170,0.116600,0.131300,0.146000,0.22260
compactness_worst,569.0,0.254265,0.157336,0.027290,0.147200,0.211900,0.339100,1.05800
concavity_worst,569.0,0.272188,0.208624,0.000000,0.114500,0.226700,0.382900,1.25200
concave points_worst,569.0,0.114606,0.065732,0.000000,0.064930,0.099930,0.161400,0.29100
symmetry_worst,569.0,0.290076,0.061867,0.156500,0.250400,0.282200,0.317900,0.66380
fractal_dimension_worst,569.0,0.083946,0.018061,0.055040,0.071460,0.080040,0.092080,0.20750

# 9. Vérification et traitement des valeurs manquantes

In [12]:
cancer.isnull().sum().sort_values(ascending=False)

diagnosis(1=m, 0=b)        0
compactness_se             0
symmetry_worst             0
concave points_worst       0
concavity_worst            0
compactness_worst          0
smoothness_worst           0
area_worst                 0
perimeter_worst            0
texture_worst              0
radius_worst               0
fractal_dimension_se       0
symmetry_se                0
concave points_se          0
concavity_se               0
smoothness_se              0
radius_mean                0
area_se                    0
perimeter_se               0
texture_se                 0
radius_se                  0
fractal_dimension_mean     0
symmetry_mean              0
concave points_mean        0
concavity_mean             0
compactness_mean           0
smoothness_mean            0
area_mean                  0
perimeter_mean             0
texture_mean               0
fractal_dimension_worst    0
dtype: int64

# 10. Analyse Univariée

## Variable : diagnosis(1=m, 0=b)

### - vérification du type de distribution

In [15]:
# Renommer la varible dépendante
cancer = cancer.rename(columns={"diagnosis(1=m, 0=b)": "diagnosis"})

In [16]:
total = cancer.diagnosis.value_counts()
percent1 = cancer.diagnosis.value_counts()/len(cancer)*100
percent2 = (round(percent1, 2))
diagnosis = pd.concat([total, percent2], axis=1, keys=['Total','%'])
diagnosis

   Total      %
0    357  62.74
1    212  37.26

In [18]:
# regrouper les données en fonction de la variable d'intérêt

cancer.groupby(['diagnosis']).mean().T

diagnosis                         0            1
radius_mean               12.146524    17.462830
texture_mean              17.914762    21.604906
perimeter_mean            78.075406   115.365377
area_mean                462.790196   978.376415
smoothness_mean            0.092478     0.102898
compactness_mean           0.080085     0.145188
concavity_mean             0.046058     0.160775
concave points_mean        0.025717     0.087990
symmetry_mean              0.174186     0.192909
fractal_dimension_mean     0.062867     0.062680
radius_se                  0.284082     0.609083
texture_se                 1.220380     1.210915
perimeter_se               2.000321     4.323929
area_se                   21.135148    72.672406
smoothness_se              0.007196     0.006780
compactness_se             0.021438     0.032281
concavity_se               0.025997     0.041824
concave points_se          0.009858     0.015060
symmetry_se                0.020584     0.020472
fractal_dimension_se       0.003636     0.004062
radius_worst              13.379801    21.134811
texture_worst             23.515070    29.318208
perimeter_worst           87.005938   141.370330
area_worst               558.899440  1422.286321
smoothness_worst           0.124959     0.144845
compactness_worst          0.182673     0.374824
concavity_worst            0.166238     0.450606
concave points_worst       0.074444     0.182237
symmetry_worst             0.270246     0.323468
fractal_dimension_worst    0.079442     0.091530

# 11. Analyse Bivariée

## Variables : diagnosis & radius_mean

In [20]:
cancer.groupby(['diagnosis'])["radius_mean"].describe()

           count       mean       std     min     25%     50%    75%    max
diagnosis
0          357.0  12.146524  1.780512   6.981  11.080  12.200  13.37  17.85
1          212.0  17.462830  3.203971  10.950  15.075  17.325  19.59  28.11

## Variables : diagnosis & texture_mean

In [21]:
cancer.groupby(['diagnosis'])["texture_mean"].describe()

           count       mean       std    min      25%    50%     75%    max
diagnosis
0          357.0  17.914762  3.995125   9.71  15.1500  17.39  19.760  33.81
1          212.0  21.604906  3.779470  10.38  19.3275  21.46  23.765  39.28

## Variables : diagnosis & perimeter_mean

In [22]:
cancer.groupby(['diagnosis'])["perimeter_mean"].describe()

           count        mean        std    min     25%     50%      75%    max
diagnosis
0          357.0   78.075406  11.807438  43.79  70.870   78.18   86.100  114.6
1          212.0  115.365377  21.854653  71.90  98.745  114.20  129.925  188.5

## Variables : diagnosis & area_mean

In [23]:
cancer.groupby(['diagnosis'])["area_mean"].describe()

           count        mean         std    min    25%    50%      75%     max
diagnosis
0          357.0  462.790196  134.287118  143.5  378.2  458.4   551.10   992.1
1          212.0  978.376415  367.937978  361.6  705.3  932.0  1203.75  2501.0

## Variables : diagnosis & smoothness_mean

In [24]:
cancer.groupby(['diagnosis'])["smoothness_mean"].describe()

,count,mean,std,min,25%,50%,75%,max
diagnosis,,,,,,,,
0,357.0,0.092478,0.013446,0.05263,0.08306,0.09076,0.100700,0.1634
1,212.0,0.102898,0.012608,0.07371,0.09401,0.10220,0.110925,0.1447

## Variables : diagnosis & compactness_mean

In [25]:
cancer.groupby(['diagnosis'])["compactness_mean"].describe()

,count,mean,std,min,25%,50%,75%,max
diagnosis,,,,,,,,
0,357.0,0.080085,0.033750,0.01938,0.05562,0.07529,0.09755,0.2239
1,212.0,0.145188,0.053987,0.04605,0.10960,0.13235,0.17240,0.3454

## Variables : diagnosis & concavity_mean

In [26]:
cancer.groupby(['diagnosis'])["concavity_mean"].describe()

,count,mean,std,min,25%,50%,75%,max
diagnosis,,,,,,,,
0,357.0,0.046058,0.043442,0.00000,0.020310,0.03709,0.05999,0.4108
1,212.0,0.160775,0.075019,0.02398,0.109525,0.15135,0.20305,0.4268

## Variables : diagnosis & concave points_mean

In [27]:
cancer.groupby(['diagnosis'])["concave points_mean"].describe()

,count,mean,std,min,25%,50%,75%,max
diagnosis,,,,,,,,
0,357.0,0.025717,0.015909,0.00000,0.01502,0.02344,0.032510,0.08534
1,212.0,0.087990,0.034374,0.02031,0.06462,0.08628,0.103175,0.20120

## Variables : diagnosis & symmetry_mean

In [28]:
cancer.groupby(['diagnosis'])["symmetry_mean"].describe()

           count      mean       std     min      25%     50%      75%     max
diagnosis
0          357.0  0.174186  0.024807  0.1060  0.15800  0.1714  0.18900  0.2743
1          212.0  0.192909  0.027638  0.1308  0.17405  0.1899  0.20985  0.3040

## Variables : diagnosis & fractal_dimension_mean

In [29]:
cancer.groupby(['diagnosis'])["fractal_dimension_mean"].describe()

,count,mean,std,min,25%,50%,75%,max
diagnosis,,,,,,,,
0,357.0,0.062867,0.006747,0.05185,0.058530,0.061540,0.065760,0.09575
1,212.0,0.062680,0.007573,0.04996,0.056598,0.061575,0.067075,0.09744

## Variables : diagnosis & texture_se

In [30]:
cancer.groupby(['diagnosis'])["texture_se"].describe()

           count      mean       std     min       25%     50%      75%    max
diagnosis
0          357.0  1.220380  0.589180  0.3602  0.795900  1.1080  1.49200  4.885
1          212.0  1.210915  0.483178  0.3621  0.892825  1.1025  1.42925  3.568

## Variables : diagnosis & perimeter_se

In [31]:
cancer.groupby(['diagnosis'])["perimeter_se"].describe()

           count      mean       std    min     25%     50%      75%     max
diagnosis
0          357.0  2.000321  0.771169  0.757  1.4450  1.8510  2.38800   5.118
1          212.0  4.323929  2.568546  1.334  2.7155  3.6795  5.20625  21.980

## Variables : diagnosis & area_se

In [32]:
cancer.groupby(['diagnosis'])["area_se"].describe()

           count       mean        std     min      25%     50%    75%     max
diagnosis
0          357.0  21.135148   8.843472   6.802  15.2600  19.630  25.03   77.11
1          212.0  72.672406  61.355268  13.990  35.7625  58.455  94.00  542.20

## Variables : diagnosis & smoothness_se

In [33]:
cancer.groupby(['diagnosis'])["smoothness_se"].describe()

,count,mean,std,min,25%,50%,75%,max
diagnosis,,,,,,,,
0,357.0,0.007196,0.003061,0.001713,0.005212,0.006530,0.008534,0.02177
1,212.0,0.006780,0.002890,0.002667,0.005085,0.006209,0.007971,0.03113

## Variables : diagnosis & compactness_se

In [34]:
cancer.groupby(['diagnosis'])["compactness_se"].describe()

,count,mean,std,min,25%,50%,75%,max
diagnosis,,,,,,,,
0,357.0,0.021438,0.016352,0.002252,0.011320,0.01631,0.02589,0.1064
1,212.0,0.032281,0.018387,0.008422,0.019662,0.02859,0.03891,0.1354

## Variables : diagnosis & concavity_se

In [35]:
cancer.groupby(['diagnosis'])["concavity_se"].describe()

,count,mean,std,min,25%,50%,75%,max
diagnosis,,,,,,,,
0,357.0,0.025997,0.032918,0.00000,0.010990,0.018400,0.030560,0.3960
1,212.0,0.041824,0.021603,0.01101,0.026998,0.037125,0.050443,0.1438

## Variables : diagnosis & concave points_se

In [36]:
cancer.groupby(['diagnosis'])["concave points_se"].describe()

,count,mean,std,min,25%,50%,75%,max
diagnosis,,,,,,,,
0,357.0,0.009858,0.005709,0.000000,0.006433,0.009061,0.011870,0.05279
1,212.0,0.015060,0.005517,0.005174,0.011415,0.014205,0.017497,0.04090

## Variables : diagnosis & symmetry_se

In [37]:
cancer.groupby(['diagnosis'])["symmetry_se"].describe()

,count,mean,std,min,25%,50%,75%,max
diagnosis,,,,,,,,
0,357.0,0.020584,0.006999,0.009539,0.015600,0.01909,0.024060,0.06146
1,212.0,0.020472,0.010065,0.007882,0.014615,0.01770,0.022132,0.07895

## Variables : diagnosis & fractal_dimension_se

In [38]:
cancer.groupby(['diagnosis'])["fractal_dimension_se"].describe()

,count,mean,std,min,25%,50%,75%,max
diagnosis,,,,,,,,
0,357.0,0.003636,0.002938,0.000895,0.002074,0.002808,0.004174,0.02984
1,212.0,0.004062,0.002041,0.001087,0.002688,0.003739,0.004892,0.01284

## Variables : diagnosis & radius_worst

In [39]:
cancer.groupby(['diagnosis'])["radius_worst"].describe()

           count       mean       std    min    25%    50%      75%    max
diagnosis
0          357.0  13.379801  1.981368   7.93  12.08  13.35  14.8000  19.82
1          212.0  21.134811  4.283569  12.84  17.73  20.59  23.8075  36.04

## Variables : diagnosis & texture_worst

In [40]:
cancer.groupby(['diagnosis'])["texture_worst"].describe()

           count       mean       std    min      25%     50%    75%    max
diagnosis
0          357.0  23.515070  5.493955  12.02  19.5800  22.820  26.51  41.78
1          212.0  29.318208  5.434804  16.67  25.7825  28.945  32.69  49.54

## Variables : diagnosis & perimeter_worst

In [41]:
cancer.groupby(['diagnosis'])["perimeter_worst"].describe()

           count        mean        std    min      25%     50%     75%    max
diagnosis
0          357.0   87.005938  13.527091  50.41   78.270   86.92   96.59  127.1
1          212.0  141.370330  29.457055  85.10  119.325  138.00  159.80  251.2

## Variables : diagnosis & area_worst

In [42]:
cancer.groupby(['diagnosis'])["area_worst"].describe()

,count,mean,std,min,25%,50%,75%,max
diagnosis,,,,,,,,
0,357.0,558.899440,163.601424,185.2,447.1,547.4,670.00,1210.0
1,212.0,1422.286321,597.967743,508.1,970.3,1303.0,1712.75,4254.0

## Variables : diagnosis & smoothness_worst

In [43]:
cancer.groupby(['diagnosis'])["smoothness_worst"].describe()

,count,mean,std,min,25%,50%,75%,max
diagnosis,,,,,,,,
0,357.0,0.124959,0.020013,0.07117,0.110400,0.12540,0.137600,0.2006
1,212.0,0.144845,0.021870,0.08822,0.130475,0.14345,0.155975,0.2226

## Variables : diagnosis & compactness_worst

In [44]:
cancer.groupby(['diagnosis'])["compactness_worst"].describe()

,count,mean,std,min,25%,50%,75%,max
diagnosis,,,,,,,,
0,357.0,0.182673,0.092180,0.02729,0.112000,0.16980,0.23020,0.5849
1,212.0,0.374824,0.170372,0.05131,0.244475,0.35635,0.44785,1.0580

## Variables : diagnosis & concavity_worst

In [45]:
cancer.groupby(['diagnosis'])["concavity_worst"].describe()

,count,mean,std,min,25%,50%,75%,max
diagnosis,,,,,,,,
0,357.0,0.166238,0.140368,0.00000,0.077080,0.1412,0.221600,1.252
1,212.0,0.450606,0.181507,0.02398,0.326425,0.4049,0.556175,1.170

## Variables : diagnosis & concave points_worst

In [46]:
cancer.groupby(['diagnosis'])["concave points_worst"].describe()

,count,mean,std,min,25%,50%,75%,max
diagnosis,,,,,,,,
0,357.0,0.074444,0.035797,0.00000,0.05104,0.07431,0.097490,0.175
1,212.0,0.182237,0.046308,0.02899,0.15275,0.18200,0.210675,0.291

## Variables : diagnosis & symmetry_worst

In [47]:
cancer.groupby(['diagnosis'])["symmetry_worst"].describe()

           count      mean       std     min     25%     50%       75%     max
diagnosis
0          357.0  0.270246  0.041745  0.1566  0.2406  0.2687  0.298300  0.4228
1          212.0  0.323468  0.074685  0.1565  0.2765  0.3103  0.359225  0.6638

## Variables : diagnosis & fractal_dimension_worst

In [48]:
cancer.groupby(['diagnosis'])["fractal_dimension_worst"].describe()

,count,mean,std,min,25%,50%,75%,max
diagnosis,,,,,,,,
0,357.0,0.079442,0.013804,0.05521,0.070090,0.07712,0.085410,0.1486
1,212.0,0.091530,0.021553,0.05504,0.076302,0.08760,0.102625,0.2075